services:
  picklist-app:
    build: .
    container_name: picklist-app
    ports:
      - "8081:5000"
    env_file:
      - .env
    volumes:
      - ./exports:/app/exports
      - ./logs:/app/logs
      - ./data:/app/data
      - ./sql:/app/sql:ro
    restart: unless-stopped
